# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  CTPL_config = debug
endif
ifeq ($(config),release)
  CTPL_config = release
endif
ifeq ($(config),dist)
  CTPL_config = dist
endif

PROJECTS := CTPL

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

CTPL:
ifneq (,$(CTPL_config))
	@echo "==== Building CTPL ($(CTPL_config)) ===="
	@${MAKE} --no-print-directory -C CTPL -f Makefile config=$(CTPL_config)
endif

clean:
	@${MAKE} --no-print-directory -C CTPL -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   CTPL"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"